### PR TITLE
Add option to cache the result of the compilation to disk

### PR DESCRIPTION
**Pull request by genintho**
This pull request add an option that allow to write the results of the compilation to disk.
While not useful in watch mode, it can be a big speed up in the other mode.

I am curious to know if this is something that could be potentially be merged?

I have used sync file operation for simplicity reason, but I would be happy to refactor to use the async ones if needed.

### CODE REVIEW

**Comment by genintho** [comment]
@sokra maybe you can shim in.

**Comment by genintho** [comment]
@sokra friendly bump :smile:

**Comment by michael-ciniawsky** [comment]
@genintho Please close and reopen the PR to trigger the CLA Bot again, rebase and yep asnyc would be better, but before you but futher effort into it plase await opinions from other reviewers. My Questions is if it is really necessary and if `this.cacheable()` (webpack Loader API) would be the better choice / applies here 😛

**Comment by michael-ciniawsky** [comment]
@genintho Closing until feedback is provided, feel free to reopen then 😛

**Comment by genintho** [comment]
Webpack `this.cacheable()` method does not provide a way to write to disk, and can useful only for incremental build, not first, cold build.

It is kind of confirmed by the most voted feature for webpack: Persistent cache
https://webpack.js.org/vote/

**Pull request closed without merging**
