### PR TITLE
docs(README): refactor for webpack v2

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
[README](https://github.com/michael-ciniawsky/coffee-loader/tree/readme)

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@TheLarkInn @SpaceK33z ping 😛

**Comment by d3viant0ne** [comment]
imo - anything that doesn't have a person assigned to maintenance should just list the contrib admin team as opposed to Tobias

**Comment by michael-ciniawsky** [comment]
@d3viant0ne Under with @ I can ping webpack-contrib admin ?

**Comment by d3viant0ne** [comment]
`@webpack-contrib/admin-team` though for the sake of consistency, just use the same setup we have for maintainers. I'll do up the html for all the admins in a sec.

**Comment by d3viant0ne** [comment]
@michael-ciniawsky 

```

<h2 align="center">Maintainers</h2>

<table>
  <tbody>
    <tr>
      <td align="center">
        <img width="150" height="150"
        src="https://avatars3.githubusercontent.com/u/166921?v=3&s=150">
        </br>
        <a href="https://github.com/bebraw">Juho Vepsäläinen</a>
      </td>
      <td align="center">
        <img width="150" height="150"
        src="https://avatars2.githubusercontent.com/u/8420490?v=3&s=150">
        </br>
        <a href="https://github.com/d3viant0ne">Joshua Wiens</a>
      </td>
      <td align="center">
        <img width="150" height="150"
        src="https://avatars3.githubusercontent.com/u/533616?v=3&s=150">
        </br>
        <a href="https://github.com/SpaceK33z">Kees Kluskens</a>
      </td>
      <td align="center">
        <img width="150" height="150"
        src="https://avatars3.githubusercontent.com/u/3408176?v=3&s=150">
        </br>
        <a href="https://github.com/TheLarkInn">Sean Larkin</a>
      </td>
    </tr>
  <tbody>
</table>


```

**Comment by michael-ciniawsky** [comment]
@d3viant0ne done

**Comment by d3viant0ne** [comment]
Looks like the CLA assistant just got turned back on :)

**Pull request merged**
